### PR TITLE
Show packages through winget

### PR DESCRIPTION
**Pull request by rashil2000**
As per #83

### CODE REVIEW

**Comment by jcwillox** [comment]
Cool, code looks fine, except you forgot to add package manager name `"$wingetpkg (winget)"`, and based on my output at least there are only 3 lines to remove so it should be `(winget list | Measure-Object).Count - 3`

The other thing is while it makes sense for `winget` to be enabled by default it is very slow, about `3.1 seconds` cold and `1.3 seconds` hot, so we may not want it enabled by default 🤷‍♂️

**Comment by rashil2000** [comment]
> ...add package manager name `$wingetpkg (winget)`...

This was actually intentional. The winget listing does not show packages installed by winget, it shows all the packages ever installed on the machine. (It mirrors the Programs list in Control Panel).

In my case I had observed two newlines in the beginning, then a header line, then the horizontal divider. So this makes it 4 extra lines. (both in Windows PowerShell and PowerShell Core)

Yes, I do agree that we should not have winget shown by default, since it fetches all those programs it takes quite some time.

**Comment by rashil2000** [comment]
> ...otherwise filter only rows that have winget as their source (i.e. lines that end with winget).

That's not how it works. The entries that have winget as their source just means that that package is available in winget repos. It does not mean that that package has been _installed through_ winget. I have 5 out of 140 programs that mention winget in their source, but 0 of them were installed _via winget_. I think what needs to be understood is that winget is not a traditional 'package manager', it's more of a generic program manager. Or, to be more pedantic, it's a CLI version of Control Panel's Programs page. And people using winget are most likely to be aware of this distinction. Mentioning `(winget)` in bracket would just give the false impression that they have been explicitly installed via winget, like scoop and choco.

And also, I'm on the latest version, v1.0.11451.

**Comment by jcwillox** [comment]
Well, no package can "technically" be installed through winget and there's no way to differentiate between a package installed through winget or not, just whether they **can** be installed/updated through winget.

> Mentioning `(winget)` in bracket would just give the false impression that they have been explicitly installed via winget, like scoop and choco.

If you're listing all packages then I get what you mean, but saying nothing and listing it in the packages section is not ideal either, but I suppose if this is something people manually enable then they'll at least be able to tell what it refers to.

**Comment by rashil2000** [comment]
> ...but I suppose if this is something people manually enable then they'll at least be able to tell what it refers to.

Exactly. This is also another reason to keep it off by default I guess.

**Comment by rashil2000** [comment]
I have improved the counting part a bit and disabled winget by default.

**Pull request merged**
