### PR TITLE
Optimize battery reporting

### LINKED ISSUE #96: Make battery reports faster
I discovered this:

```powershell
Add-Type -Assembly System.Windows.Forms
[System.Windows.Forms.SystemInformation]::PowerStatus
```

We can replace the (unreliably slower) WMI calls with this simple environment variable.

### PR DESCRIPTION
**Pull request by rashil2000**
Closes #96

### CODE REVIEW

**Review by jcwillox — APPROVED** [review]
Works great 👍, I think it's time to publish a new release.

**Comment by rashil2000** [comment]
Hey, slow down!

You forgot to bump the version number and GUID in the script, again 😢

**Comment by rashil2000** [comment]
It's only been 15min, please force push the tag 2.3.0 with the changes

**Comment by jcwillox** [comment]
Oh whoops, my bad, totally forgot about that, really wish it was automated 🤦‍♂️

**Pull request merged**
