### PR TITLE
Solve incorrect resolution when dpi is set

### PR DESCRIPTION
**Pull request by HO-COOH**
I have this maybe over-convoluted approach to solve #76 
Also see [my comment](https://github.com/kiedtl/winfetch/issues/76#issuecomment-964814864)

But anyway, it does solves the issue.
Here's a screenshot of the result.
image

### CODE REVIEW

**Comment by HO-COOH** [comment]
@rashil2000 This is what before was like. I have two 3840*2160 screens scaled at 200%, so it was showing 1920*1080, one at 150% so it was showing 2560*1440, one 2560*1440 and one 1080p both scaled at 100% respectively. So it was a mess.

image

For performance, this is before
```
PS C:\Users\Peter\Desktop\winfetch> Measure-Command { .\winfetch.ps1}


Days              : 0
Hours             : 0
Minutes           : 0
Seconds           : 0
Milliseconds      : 488
Ticks             : 4882514
TotalDays         : 5.65105787037037E-06
TotalHours        : 0.000135625388888889
TotalMinutes      : 0.00813752333333333
TotalSeconds      : 0.4882514
TotalMilliseconds : 488.2514
```

After
```
PS C:\Users\Peter\Desktop\winfetch> Measure-Command { .\winfetch.ps1}


Days              : 0
Hours             : 0
Minutes           : 0
Seconds           : 0
Milliseconds      : 674
Ticks             : 6742181
TotalDays         : 7.80345023148148E-06
TotalHours        : 0.000187282805555556
TotalMinutes      : 0.0112369683333333
TotalSeconds      : 0.6742181
TotalMilliseconds : 674.2181
```

**Comment by HO-COOH** [comment]
Btw, with this approach I can easily add refresh rate to it as #116

**Comment by rashil2000** [comment]
Can you merge with latest master? Your branch is very behind.

**Comment by rashil2000** [comment]
@HO-COOH any updates?

We are planning to make a release. It would be good to include this fix in it.

**Comment by HO-COOH** [comment]
It's not an issue of my editor. I cloned this project, run it fresh, it's producing the error
image

**Comment by rashil2000** [comment]
What is your $OutputEncoding? And PowerShell version?

**Comment by HO-COOH** [comment]
> What is your $OutputEncoding? And PowerShell version?

image

**Comment by rashil2000** [comment]
There is a bug in Windows PowerShell version 5.1. To work around this, you can put this line in your $PROFILE:
```pwsh
if ($PSVersionTable.PSVersion.Major -le 5) { $OutputEncoding = [System.Text.Encoding]::UTF8 }
```

**Comment by HO-COOH** [comment]
image

Nope, still the same. But maybe this should be created as a separate issue, and you can merge this PR first.

**Comment by rashil2000** [comment]
Have you tried cloning the repo and running it in PowerShell 7+?

**Comment by HO-COOH** [comment]
@rashil2000 Just tried. It runs fine on Powershell 7, but I would suggest to make it compatible with the powershell 5.1 that comes preinstalled.

**Comment by rashil2000** [comment]
It does work on PowerShell 5.1 😅 (I do all my winfetch work on 5.1).

As I said, there are some bugs in PS 5.1 regarding codepages/encoding that you need to workaround yourself (depending on region/language). It is unlikely that these will be fixed given that 5.1 receives no updates.

**Comment by HO-COOH** [comment]
I tried it on another PC that has Windows 11, Simplified Chinese fresh installed, it also doesn't run in Powershell 5.1.🤔

**Comment by rashil2000** [comment]
> Simplified Chinese

Likely that PS 5.1 has issues with this language. If you can't solve it through changing codepage/encoding, I'm sorry there's nothing I or winfetch can do about it. Your only solution is to use a better and more up to date PS 7.

**Comment by HO-COOH** [comment]
The thing is I am having issue with the US version, and that's likely to bring issues with quite a lot of users. The thing you can do is remove that Microsoft fallback logo, that's the reason my PR was originally based on the released 2.3 branch.

**Comment by rashil2000** [comment]
The logo had been requested by many people for a long time, that's why it was added. I'm reluctant to remove it based on a single report yet.

@jcwillox any thoughts?

In the meanwhile, let's not stall this PR because it's unrelated here. I'd recommend you to use PS 7 to continue with the review here. For the encoding problem, please create a new issue.

**Comment by HO-COOH** [comment]
Yeah ok, other than this, my PR runs fine on Powershell 7.

**Comment by rashil2000** [comment]
> Could you please open the PR from a fresh branch (created from latest master)?

Because there are a lot of (unrelated) changes in the current PR

**Pull request closed without merging**
